#cloud-config
# ============================================================
# UBUNTU SERVER AUTOINSTALL — SETUP PERSONAL
# ============================================================

autoinstall:
  version: 1

  # ==========================================================
  # LOCALIZACIÓN
  # ==========================================================
  locale: es_CL.UTF-8
  timezone: America/Santiago

  keyboard:
    layout: latam

  # ==========================================================
  # IDENTIDAD
  # ==========================================================
  identity:
    hostname: personal-ubuntu
    username: antocreed777
    # Generar con: mkpasswd -m sha-512
    password: "$6$REEMPLAZAR_POR_HASH_REAL"

  # ==========================================================
  # ==========================================================

  updates: security

  drivers:
    install: true

  # ==========================================================
  # SSH
  # ==========================================================
  ssh:
    install-server: true
    allow-pw: true

  # ==========================================================
  # PAQUETES
  # ==========================================================
  packages:

    # ===============================
    # GUI
    # ===============================
    - ubuntu-desktop-minimal

    # ===============================
    # SISTEMA BASE
    # ===============================
    - ca-certificates
    - gnupg
    - curl
    - wget
    - unzip
    - git
    - unattended-upgrades

    # ===============================
    # DESARROLLO NATIVO
    # ===============================
    - build-essential
    - clang
    - gdb
    - valgrind

    # ===============================
    # PYTHON
    # ===============================
    - python3
    - python3-pip
    - python3-venv
    - python3-dev
    - pipx

    # ===============================
    # UTILIDADES PRODUCTIVIDAD
    # ===============================
    - vim
    - lsd
    - btop
    - htop
    - ncdu
    - ripgrep
    - bat

  # ==========================================================
  # SNAPS
  # ==========================================================
  snaps:
    - name: code
      channel: stable
      classic: true

  # ==========================================================
  # CONFIGURACIÓN FINAL
  # ==========================================================
  late-commands:

  # Clonar repo en que se encuentran los scripts de postinstalación
  - curtin in-target -- bash -lc 'rm -rf /opt/my-installer && git clone --depth 1 https://github.com/AntoCreed777/My-Custom-Ubuntu-Installer.git /opt/my-installer'

  # Ejecutar el script principal de postinstalación
  - curtin in-target -- bash -lc 'chmod +x /opt/my-installer/scripts/main.sh && /opt/my-installer/scripts/main.sh --user antocreed777 |& tee /var/log/postinstall.log'
